### ISSUE TITLE
classifiers and numeric results

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-asls-soil-prof#6]
The YB assigns classifiers to numeric ranges 
eg see size  "2"  "Medium" for results in range of 5 - 15 mm

if data providers give a number as a result eg "7 mm", then we are storing it as that. 

We were not sure if "medium" was more meaningful as a result to some soil folk? we stored this as a separate result (for one dataset, at least) - Pretty cumbersome 

Don't think this has implications for YB encoding, but just flagging FYI as data transfer issue

@bsimons14 may have further comment here

**Comment by dr-shorthair** [comment]
You must select a classifier from the system in use (i.e. "2" "Medium" if the value is "7 mm"). 
If you also want to store the 7mm value then that is a comment or a local extension.

**Comment by bsimons14** [comment]
Federation University is storing measurements as actual values or ranges along with their UoM (e.g. "7" or "5 - 15"). As a separate observation they are storing the 'term' (e.g. "Medium"). However, they are are not separately referring to the YB code (e.g. "2"). Access to the YB code if required should be by the skos:Notation included with the pref:Label (e.g. "Medium").

**Comment by dr-shorthair** [comment]
The goal of providing the ASLS as an online resource is to allow you to use URIs rather than codes. 
That way you can get the label or the code (notation) by dereferencing the URI. 

I'm aware that the ASLS URIs do not currently resolve because registry.it.csiro.au was taken offline just before Xmas because of a 'critical security vulnerability' in log4j . I understand there is a plan to fix this, but not sure on timing.

**Comment by bsimons14** [comment]
FedUni uses the URIs to the resource, not the term or code.

**Comment by meganrwong** [comment]
noted - storing measurements as actual values or ranges along with their UoM, that is organisational DB business decision. ASLS is being provided as URIs -  users can get the label or the code (notation) by dereferencing the URI.
